### PR TITLE
Add Alexnet Example

### PR DESCRIPTION
**Pull request by dcslin**

### CODE REVIEW

**Comment by chrishkchris** [comment]
Here is a test on alexnet using cifar10:

```
(singapy36) dcsysh@panda11:~/singa/examples/cnn$ python train.py alexnet cifar10
Starting Epoch 0:
Training loss = 1611.267456, training accuracy = 0.225992
Evaluation accuracy = 0.307091, Elapsed Time = 69.078020s
Starting Epoch 1:
Training loss = 1349.916016, training accuracy = 0.356514
Evaluation accuracy = 0.385917, Elapsed Time = 69.427504s
Starting Epoch 2:
Training loss = 1189.298340, training accuracy = 0.437600
Evaluation accuracy = 0.456430, Elapsed Time = 69.476516s
```

**Comment by chrishkchris** [comment]
One point to notice is that:
Currently in SINGA, ReLU is stateless, i.e. we don't need to initialize a python object for ReLU before use (and we cannot create an instance of ReLU).

**Comment by dcslin** [comment]
not able to reproduce issue
https://github.com/apache/singa/issues/681

thus tried to implement alexnet and it works fine

maybe we should define issue reporting format to better undertanding these kind of the issues:
example of issue reporting format: 
https://github.com/pytorch/pytorch/issues/new?template=bug-report.md

**Comment by chrishkchris** [comment]
I recommend this one is ready for merge, it is good to have Alexnet for research purpose

**Comment by chrishkchris** [comment]
@dcslin 
I suggest you add an line in Alexnet.py 
# the code is modified from
# https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py

Please consider follow this example: https://github.com/apache/singa/blob/master/examples/cnn/model/resnet.py#L21

**Pull request merged**
