### PR TITLE
Broadcast for Mult

### PR DESCRIPTION
**Pull request by dcslin**
Added broadcasted() flag for tensor
Added broadcast to mult
Refactored gpu traverse unary

### CODE REVIEW

**Comment by dcslin** [comment]
Hi @joddiy , could you please help to test the testcase?

**Comment by joddiy** [comment]
Thanks, shicong, let me check.

**Comment by joddiy** [comment]
Hi, shicong, thanks for your code, it works fine for MatMul, however, it seems the `sub` has some problem now. please use the following test case to check:


```    
    def high_dim_helper(self, dev):
        configs = [
            # [(1, 12, 7, 64), (1, 12, 64, 7)],
            # [(1, 7, 768), (768, 768)],
            # generate test
            [(1), (1, 1, 1, 7)],
        ]
        ops = [
            # [np.add, autograd.add],
            [np.subtract, autograd.sub],
            # [np.matmul, autograd.matmul],
            # [np.divide, autograd.div],
        ]
        for config in configs:
            for op in ops:
                X = np.random.random(config[0]).astype(np.float32)
                x = tensor.from_numpy(X)
                x.to_device(dev)

                W = np.random.random(config[1]).astype(np.float32)
                w = tensor.from_numpy(W)
                w.to_device(dev)

                y_t = op[0](X, W)
                y = op[1](x, w)
                np.testing.assert_array_almost_equal(tensor.to_numpy(y), y_t, 3)

    def test_high_dim_cpu(self):
        self.high_dim_helper(cpu_dev)

    @unittest.skipIf(not singa_wrap.USE_CUDA, 'CUDA is not enabled')
    def test_high_dim_gpu(self):
        self.high_dim_helper(gpu_dev)
```

**Comment by dcslin** [comment]
> Hi, shicong, thanks for your code, it works fine for MatMul, however, it seems the `sub` has some problem now. please use the following test case to check:
> 
> ```
>     def high_dim_helper(self, dev):
>         configs = [
>             # [(1, 12, 7, 64), (1, 12, 64, 7)],
>             # [(1, 7, 768), (768, 768)],
>             # generate test
>             [(1), (1, 1, 1, 7)],
>         ]
>         ops = [
>             # [np.add, autograd.add],
>             [np.subtract, autograd.sub],
>             # [np.matmul, autograd.matmul],
>             # [np.divide, autograd.div],
>         ]
>         for config in configs:
>             for op in ops:
>                 X = np.random.random(config[0]).astype(np.float32)
>                 x = tensor.from_numpy(X)
>                 x.to_device(dev)
> 
>                 W = np.random.random(config[1]).astype(np.float32)
>                 w = tensor.from_numpy(W)
>                 w.to_device(dev)
> 
>                 y_t = op[0](X, W)
>                 y = op[1](x, w)
>                 np.testing.assert_array_almost_equal(tensor.to_numpy(y), y_t, 3)
> 
>     def test_high_dim_cpu(self):
>         self.high_dim_helper(cpu_dev)
> 
>     @unittest.skipIf(not singa_wrap.USE_CUDA, 'CUDA is not enabled')
>     def test_high_dim_gpu(self):
>         self.high_dim_helper(gpu_dev)
> ```

Checking

**Comment by dcslin** [comment]
@joddiy , this should be working now

**Comment by joddiy** [comment]
> @joddiy , this should be working now

Thanks, shicong, it works fine now.

**Pull request merged**
