### PR TITLE
Changes in sonnx.py and Added ShufflenetV2.py

### PR DESCRIPTION
**Pull request by Shashankwer**
Changed contents in sonnx.py as follows:
ceil_mode = onnx_node.getattr("ceil_mode",0)
        count_include_pad = onnx_node.getattr("count_include_pad",0)
        if ceil_mode!=0 or count_include_pad!=0:
            raise ValueError("Not implemented yet for count_include_pad or ceil_mode")

Added Shufflenetv2.py

SONNX implementation of ONNX shufflenetv2 from https://github.com/onnx/models/raw/master/vision/classification/shufflenet/model/shufflenet-v2-10.tar.gz

### CODE REVIEW

**Comment by joddiy** [comment]
@Shashankwer 
Hi, please refer to our code style to reformat your commit.

https://github.com/apache/singa-doc/blob/master/docs-site/docs/contribute-code.md

**Comment by Shashankwer** [comment]
Hi @joddiy,

Updating sonnx.py gives an error Class 'TensorProto' has no 'BOOL' member in pylint. Is it possible to add no-member under disable parameter in .pylintrc of the project to suppress the error?
The commit has been made reformatting the code and no changes were made in .pylintrc

Thanks,
Shashank

**Comment by joddiy** [comment]
Hi, @Shashankwer, thanks for the report on this issue. However, since I've refactored lots of code in `dev` branch, as well as this issue. So I think it's a good time to switch our work from `master` branch to `dev` branch.

And for an example, I've re-code this PR to dev branch in PR https://github.com/apache/singa/pull/735, you can compare the code and try to learn the implement in `dev` branch.

> Hi @joddiy,
> 
> Updating sonnx.py gives an error Class 'TensorProto' has no 'BOOL' member in pylint. Is it possible to add no-member under disable parameter in .pylintrc of the project to suppress the error?
> The commit has been made reformatting the code and no changes were made in .pylintrc
> 
> Thanks,
> Shashank

**Comment by Shashankwer** [comment]
Hi @joddiy ,

Thanks, will make further updates on dev branches. 

Thanks and Regards,
Shashank Nigam

**Comment by joddiy** [comment]
> Hi @joddiy ,
> 
> Thanks, will make further updates on dev branches.
> 
> Thanks and Regards,
> Shashank Nigam

Hi, @Shashankwer , can you close this PR, since we have moved the code to https://github.com/apache/singa/pull/735

**Pull request closed without merging**
