### PR TITLE
hotfix on dev branch (remove of duplicate variable)

### PR DESCRIPTION
**Pull request by chrishkchris**
Maybe there are some errors in DNNL needed to be fixed before functioning correctly.

I currently have solved a build error due to reassign of variable, so now I can built the code. The c test case test_singa.o and python mlp.py can now pass.

There are two more errors I encountered but I did not solve yet
1. mnist_cnn (after changing to cpu), it hangs.
2. test_operation.py
```
ubuntu@ip-172-31-24-48:~/singa/test/python$ python3 test_operation.py
.......................................Segmentation fault (core dumped)
```

### CODE REVIEW

**Comment by chrishkchris** [comment]
@dcslin when I set up the docker container in panda5, the following error is encountered.

```
[ 51%] Building CXX object src/CMakeFiles/singa_objects.dir/model/metric/accuracy.cc.o
[ 51%] Building CXX object src/CMakeFiles/singa_objects.dir/model/updater/local_updater.cc.o
[ 52%] Building CXX object src/CMakeFiles/singa_objects.dir/model/updater/updater.cc.o
[ 52%] Building CXX object src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o
/root/singa/src/model/operation/batchnorm.cc: In constructor 'singa::CudnnBatchNormHandle::CudnnBatchNormHandle(float, const singa::Tensor&)':
/root/singa/src/model/operation/batchnorm.cc:246:12: error: 'transform' is not a member of 'std'
       std::transform(alg.begin(), alg.end(), alg.begin(), toupper);
            ^~~~~~~~~
src/CMakeFiles/singa_objects.dir/build.make:972: recipe for target 'src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o' failed
make[2]: *** [src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o] Error 1
make[1]: *** [src/CMakeFiles/singa_objects.dir/all] Error 2
CMakeFiles/Makefile2:131: recipe for target 'src/CMakeFiles/singa_objects.dir/all' failed
make: *** [all] Error 2
Makefile:129: recipe for target 'all' failed
The command '/bin/sh -c cd $HOME/singa/build && make && make install' returned a non-zero code: 2
```

**Comment by nudles** [comment]
```error: 'transform' is not a member of 'std'```
Did you include ```#include <algorithm>  ```

**Comment by chrishkchris** [comment]
> error: 'transform' is not a member of 'std'
> Did you include #include <algorithm>

no, I am now trying to add #include <algorithm> in batchnorm.h

**Comment by chrishkchris** [comment]
> @dcslin when I set up the docker container in panda5, the following error is encountered.
> [ 51%] Building CXX object src/CMakeFiles/singa_objects.dir/model/metric/accuracy.cc.o
> [ 51%] Building CXX object src/CMakeFiles/singa_objects.dir/model/updater/local_updater.cc.o
> [ 52%] Building CXX object src/CMakeFiles/singa_objects.dir/model/updater/updater.cc.o
> [ 52%] Building CXX object src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o
> /root/singa/src/model/operation/batchnorm.cc: In constructor 'singa::CudnnBatchNormHandle::CudnnBatchNormHandle(float, const singa::Tensor&)':
> /root/singa/src/model/operation/batchnorm.cc:246:12: error: 'transform' is not a member of 'std'
>        std::transform(alg.begin(), alg.end(), alg.begin(), toupper);
>             ^~~~~~~~~
> src/CMakeFiles/singa_objects.dir/build.make:972: recipe for target 'src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o' failed
> make[2]: *** [src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o] Error 1
> make[1]: *** [src/CMakeFiles/singa_objects.dir/all] Error 2
> CMakeFiles/Makefile2:131: recipe for target 'src/CMakeFiles/singa_objects.dir/all' failed
> make: *** [all] Error 2
> Makefile:129: recipe for target 'all' failed
> The command '/bin/sh -c cd $HOME/singa/build && make && make install' returned a non-zero code: 2

@dcslin @nudles Sorry, when I checked the dockerfile, I found that the dockerfile clones the master branch to build the code. So this error is unrelated to the dev branch. This first comment of this PR was not using docker so it reflects the dev branch. Sorry for confusion.

**Comment by chrishkchris** [comment]
> error: 'transform' is not a member of 'std'
> Did you include #include 
> 
> no, I am now trying to add #include <algorithm> in batchnorm.h

After 


> @dcslin when I set up the docker container in panda5, the following error is encountered.
> [ 51%] Building CXX object src/CMakeFiles/singa_objects.dir/model/metric/accuracy.cc.o
> [ 51%] Building CXX object src/CMakeFiles/singa_objects.dir/model/updater/local_updater.cc.o
> [ 52%] Building CXX object src/CMakeFiles/singa_objects.dir/model/updater/updater.cc.o
> [ 52%] Building CXX object src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o
> /root/singa/src/model/operation/batchnorm.cc: In constructor 'singa::CudnnBatchNormHandle::CudnnBatchNormHandle(float, const singa::Tensor&)':
> /root/singa/src/model/operation/batchnorm.cc:246:12: error: 'transform' is not a member of 'std'
> std::transform(alg.begin(), alg.end(), alg.begin(), toupper);
> ^~~~~~~~~
> src/CMakeFiles/singa_objects.dir/build.make:972: recipe for target 'src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o' failed
> make[2]: *** [src/CMakeFiles/singa_objects.dir/model/operation/batchnorm.cc.o] Error 1
> make[1]: *** [src/CMakeFiles/singa_objects.dir/all] Error 2
> CMakeFiles/Makefile2:131: recipe for target 'src/CMakeFiles/singa_objects.dir/all' failed
> make: *** [all] Error 2
> Makefile:129: recipe for target 'all' failed
> The command '/bin/sh -c cd $HOME/singa/build && make && make install' returned a non-zero code: 2
> 
> @dcslin @nudles Sorry, when I checked the dockerfile, I found that the dockerfile clones the master branch to build the code. So this error is unrelated to the dev branch. This first comment of this PR was not using docker so it reflects the dev branch. Sorry for confusion.

@dcslin @nudles so the problem of the docker in dev branch was that it used DNNL and the master branch code. I will change it by locally adding "git checkout dev" for the debug in this PR.

**Comment by chrishkchris** [comment]
> Maybe there are some errors in DNNL needed to be fixed before functioning correctly.
> I currently have solved a build error due to reassign of variable, so now I can built the code. The c test case test_singa.o and python mlp.py can now pass.
> There are two more errors I encountered but I did not solve yet
> 
> mnist_cnn (after changing to cpu), it hangs.
> test_operation.py
> 
> ubuntu@ip-172-31-24-48:~/singa/test/python$ python3 test_operation.py
> .......................................Segmentation fault (core dumped)

@dcslin 
I tried it in panda 5 using docker, it was the same as that in AWS without docker
```
root@04484c49d78c:~/singa/test/python# python3 test_operation.py
.......................................Segmentation fault (core dumped)
```

**Comment by dcslin** [comment]
HI @chrishkchris , there is error in TestPythonOperation.test_batchnorm2d_cpu. I am checking

**Comment by chrishkchris** [comment]
> HI @chrishkchris , there is error in TestPythonOperation.test_batchnorm2d_cpu. I am checking
@dcslin 
the batchnorm2d_gpu also has error of dnnl, seems due to the control logic 
```
ubuntu@ip-172-31-35-63:~/singa/test/python$ python3 test_operation.py TestPythonOperation.test_batchnorm2d_gpu
terminate called after throwing an instance of 'dnnl::error'
  what():  attempt to use uninitialized object
Aborted (core dumped)
```

**Comment by dcslin** [comment]
Hi @chris, some errors are due to enabling both USE DNNL and USE CUDNN. I fixed them in https://github.com/apache/singa/pull/590

**Comment by dcslin** [comment]
Thus `test/python/test_api.py` is passing with no error, meaning C++ side should be fine. As for `test_operation.py`, I think there are some changes in `autograd.py`...

**Comment by chrishkchris** [comment]
> Thus test/python/test_api.py is passing with no error, meaning C++ side should be fine. As for test_operation.py, I think there are some changes in autograd.py...

@dcslin great! thank you so much! 

@nudles merging this PR #589 and PR #590 will fix two errors, I will re-test after merging the two bug fix PRs.

**Comment by chrishkchris** [comment]
the build error due to duplicate of variable has been resolved in #590, and hence this PR can be closed. I will retest the code.

**Comment by chrishkchris** [comment]
There is an new error in cpu batchnorm, where the number of output arguments do not match with the python autograd code. This PR simply fix the issue.

root@b8dfa5473dea:~/dcsysh/singa/test/python# python3 test_operation.py
................................................................E............................................................
======================================================================
ERROR: test_batchnorm2d_cpu (__main__.TestPythonOperation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_operation.py", line 286, in test_batchnorm2d_cpu
    y = batchnorm_0(cpu_input_tensor)
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1502, in __call__
    self.running_var,
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1581, in batchnorm_2d
    return _BatchNorm2d(handle, running_mean, running_var)(x, scale, bias)[0]
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 244, in __call__
    return self._do_forward(*xs)
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 294, in _do_forward
    ys = self.forward(*xs)
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1532, in forward
    self.running_var)
ValueError: too many values to unpack (expected 3)

----------------------------------------------------------------------
Ran 125 tests in 0.766s

FAILED (errors=1)

root@b8dfa5473dea:~/dcsysh/singa/examples/autograd# python3 resnet.py
Start intialization............
  0%|                                                                                                                                                                                  | 0/100 [00:26<?, ?it/s]
Traceback (most recent call last):
  File "resnet.py", line 278, in <module>
    x = model(tx)
  File "resnet.py", line 179, in __call__
    x = self.bn1(x)
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1502, in __call__
    self.running_var,
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1581, in batchnorm_2d
    return _BatchNorm2d(handle, running_mean, running_var)(x, scale, bias)[0]
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 244, in __call__
    return self._do_forward(*xs)
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 294, in _do_forward
    ys = self.forward(*xs)
  File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1532, in forward
    self.running_var)

**Pull request closed without merging**
