### PR TITLE
Add roberta model

### PR DESCRIPTION
**Pull request by joddiy**

### CODE REVIEW

**Comment by joddiy** [comment]
it seems the model has some problems, I have reported an issue to the onnx, hope they can check it...

https://github.com/onnx/models/issues/351

**Comment by joddiy** [comment]
Hi, shicong, @dcslin , it seems, we need to upgrade the Matmul operator to support high dimensions.

For eaxmple:
(1, 7, 768) * (768, 768)
(1, 12, 7, 64) * (1, 12, 64, 7)

**Comment by dcslin** [comment]
> Hi, shicong, @dcslin , it seems, we need to upgrade the Matmul operator to support high dimensions.
> 
> For eaxmple:
> (1, 7, 768) * (768, 768)
> (1, 12, 7, 64) * (1, 12, 64, 7)

We need to add broadcasting to matmul. still checking

**Comment by joddiy** [comment]
ready to merge after #794

**Pull request merged**
