### PR TITLE
SINGA-500 add onnx example models

### PR DESCRIPTION
**Pull request by joddiy**

### CODE REVIEW

**Comment by joddiy** [comment]
cannot merge yet, still need to add GlobalAveragePool op.

**Comment by nudles** [comment]
you can mark it as a draft like #580

**Comment by nudles** [comment]
Can this be merged?
Pls fix the conflicts and format the code.

**Comment by joddiy** [comment]
> Can this be merged?
> Pls fix the conflicts and format the code.

cannot yet, after merge the gemm, I will continue to work on this PR.

**Comment by joddiy** [comment]
> you can mark it as a draft like #580

cannot convert an existing PR to draft :), https://github.com/isaacs/github/issues/1547

I will be careful next time.

**Pull request closed without merging**
