### PR TITLE
Implement Squeezenet using Squeezenet1.1

### PR DESCRIPTION
**Pull request by agnesnatasya**
Implemented Squeezenet model using Squeezenet1.1 model in ONNX model zoo. 
As compared to the inference here https://github.com/onnx/models/blob/master/vision/classification/imagenet_inference.ipynb , which resizes the image to 256 and crop the 224 in the center, I resized the image to 224 and take all these 224 pixels as an input to the model. It gave different result when I tried these 2 approaches, but the second one gives more similar result. Thus, I choose the second one. Is there any significant impact of this difference?

### CODE REVIEW

**Comment by nudles** [comment]
@joddiy  pls help review.

**Comment by joddiy** [comment]
> @joddiy pls help review.

sure, I'll review it soon. I'm working on the `test_operations.py`. I guess I will review this PR today later.

@agnesnatasya, Thanks for your commit, if you're free, you can continue to the next model. Please leave a comment about the model you chose in the #700 .

**Comment by joddiy** [comment]
@agnesnatasya Thanks for your help! I've reviewed the code, it's ready to merge into the master. @nudles 

And the result seems fine:

image

**Comment by agnesnatasya** [comment]
Thank you @joddiy for the review, will make the change and will push again

**Comment by agnesnatasya** [comment]
@joddiy The guide stated that "After the configuration, linting should be automatically applied when editing source code file". There is no warning in the "PROBLEMS" tab, but there are some warnings when I run pylint from terminal. However, other files like vgg16.py, also have these warnings when I run pylint on it. 

Have reformatted with yapf.

**Comment by nudles** [comment]
@agnesnatasya @joddiy thanks!

**Pull request merged**
