### PR TITLE
Broadcast cudnn test passing

### PR DESCRIPTION
**Pull request by dcslin**

### CODE REVIEW

**Comment by joddiy** [comment]
Hi, shicong, I have add some test cases in autograd. It seems this implement works fine for __add__, __sub__, but return all zero values for __mul__. can you check it about?

**Comment by joddiy** [comment]
Hi, shicong, please use this to test __mul__
```
def test_tensor_add_api(self):

    def _run_test(s1, s2):
        x_0 = np.random.random(s1).astype(np.float32)
        y_0 = np.random.random(s2).astype(np.float32)
        x0 = tensor.Tensor(device=gpu_dev, data=x_0)
        y0 = tensor.Tensor(device=gpu_dev, data=y_0)

        z0 = tensor._call_singa_func(singa_api.__mul__, x0.data, y0.data)

        #print(s1,s2,tensor.to_numpy(z0).shape)
        np.testing.assert_array_almost_equal(tensor.to_numpy(z0), x_0+y_0)
        return

    # 2d
    _run_test([3, 4], [3, 4])
    # 3d
    _run_test([3, 4, 5], [3, 4, 5])
    # 4d
    _run_test([3, 4, 5, 6], [3, 4, 5, 6])
    # 3d vs 1d
    _run_test([3, 4, 5], [5])
    # 3d vs 2d
    _run_test([3, 4, 5], [4, 5])
    # 4d vs 2d
    _run_test([3, 4, 5, 6], [5, 6])
    # 4d vs 3d
    _run_test([3, 4, 5, 6], [4, 5, 6])
    # 4d vs 4d
    _run_test([1, 4, 1, 6], [3, 1, 5, 6])
```

**Comment by dcslin** [comment]
Hi @joddiy thank you for the info. this is tested and test case are updated

**Comment by dcslin** [comment]
This is ready for merging

**Comment by joddiy** [comment]
ready to merge

**Pull request merged**
