### PR TITLE
Fix python and c++ test cases

### PR DESCRIPTION
**Pull request by chrishkchris**
This PR can fix the cpp test case in #761  

```
root@71ac539cda77:~/dcsysh/singa/build/bin# ./test_singa
Running main() from gtest_main.cc
[==========] Running 159 tests from 35 test cases.
[----------] Global test environment set-up.
[----------] 1 test from Accuracy
[ RUN      ] Accuracy.Compute
[       OK ] Accuracy.Compute (0 ms)
[----------] 1 test from Accuracy (0 ms total)

[----------] 3 tests from Activation
[ RUN      ] Activation.Setup
[       OK ] Activation.Setup (0 ms)
[ RUN      ] Activation.Forward
[       OK ] Activation.Forward (0 ms)
[ RUN      ] Activation.Backward
[       OK ] Activation.Backward (0 ms)
[----------] 3 tests from Activation (0 ms total)

[----------] 1 test from AdaGrad
[ RUN      ] AdaGrad.ApplyCPU
[       OK ] AdaGrad.ApplyCPU (0 ms)
[----------] 1 test from AdaGrad (0 ms total)

[----------] 3 tests from BatchNorm
[ RUN      ] BatchNorm.Setup
[       OK ] BatchNorm.Setup (0 ms)
[ RUN      ] BatchNorm.Forward
[       OK ] BatchNorm.Forward (1 ms)
[ RUN      ] BatchNorm.Backward
[       OK ] BatchNorm.Backward (0 ms)
[----------] 3 tests from BatchNorm (1 ms total)

[----------] 2 tests from BinFileWriter
[ RUN      ] BinFileWriter.Create
[       OK ] BinFileWriter.Create (236 ms)
[ RUN      ] BinFileWriter.Append
[       OK ] BinFileWriter.Append (3 ms)
[----------] 2 tests from BinFileWriter (239 ms total)

[----------] 2 tests from BinFileReader
[ RUN      ] BinFileReader.Read
[       OK ] BinFileReader.Read (0 ms)
[ RUN      ] BinFileReader.SeekToFirst
[       OK ] BinFileReader.SeekToFirst (1 ms)
[----------] 2 tests from BinFileReader (1 ms total)

[----------] 3 tests from Channel
[ RUN      ] Channel.InitChannel
[       OK ] Channel.InitChannel (0 ms)
[ RUN      ] Channel.SendStringToFile
[W d0713 t11:31:57 p11482:344 /root/dcsysh/singa/src/utils/channel.cc:70] Messages will be appended to an existed file: /tmp/test_channel
[       OK ] Channel.SendStringToFile (1 ms)
[ RUN      ] Channel.SendStringToFileAndStderr
test to both file and stderr
[       OK ] Channel.SendStringToFileAndStderr (0 ms)
[----------] 3 tests from Channel (1 ms total)

[----------] 5 tests from Concat
[ RUN      ] Concat.Setup
[       OK ] Concat.Setup (0 ms)
[ RUN      ] Concat.ForwardConcatRowCpp
[       OK ] Concat.ForwardConcatRowCpp (0 ms)
[ RUN      ] Concat.ForwardConcatColumnCpp
[       OK ] Concat.ForwardConcatColumnCpp (0 ms)
[ RUN      ] Concat.BackwardConcatRowCpp
[       OK ] Concat.BackwardConcatRowCpp (0 ms)
[ RUN      ] Concat.BackwardConcatColumn
[       OK ] Concat.BackwardConcatColumn (0 ms)
[----------] 5 tests from Concat (0 ms total)

[----------] 3 tests from Convolution
[ RUN      ] Convolution.Setup
[       OK ] Convolution.Setup (0 ms)
[ RUN      ] Convolution.Forward
[       OK ] Convolution.Forward (0 ms)
[ RUN      ] Convolution.Backward
[       OK ] Convolution.Backward (0 ms)
[----------] 3 tests from Convolution (0 ms total)

[----------] 4 tests from CppCPU
[ RUN      ] CppCPU.Constructor
[       OK ] CppCPU.Constructor (0 ms)
[ RUN      ] CppCPU.MemoryMallocFree
[       OK ] CppCPU.MemoryMallocFree (0 ms)
[ RUN      ] CppCPU.Exec
[       OK ] CppCPU.Exec (0 ms)
[ RUN      ] CppCPU.CopyData
[       OK ] CppCPU.CopyData (0 ms)
[----------] 4 tests from CppCPU (0 ms total)

[----------] 4 tests from TestSoftmaxCrossEntropy
[ RUN      ] TestSoftmaxCrossEntropy.CppForward
[       OK ] TestSoftmaxCrossEntropy.CppForward (0 ms)
[ RUN      ] TestSoftmaxCrossEntropy.CppForwardAryTarget
[       OK ] TestSoftmaxCrossEntropy.CppForwardAryTarget (0 ms)
[ RUN      ] TestSoftmaxCrossEntropy.CppBackward
[       OK ] TestSoftmaxCrossEntropy.CppBackward (0 ms)
[ RUN      ] TestSoftmaxCrossEntropy.CppBackwardAryTarget
[       OK ] TestSoftmaxCrossEntropy.CppBackwardAryTarget (1 ms)
[----------] 4 tests from TestSoftmaxCrossEntropy (1 ms total)

[----------] 1 test from CSV
[ RUN      ] CSV.EncoderDecode
[       OK ] CSV.EncoderDecode (0 ms)
[----------] 1 test from CSV (0 ms total)

[----------] 3 tests from Dense
[ RUN      ] Dense.Setup
[       OK ] Dense.Setup (0 ms)
[ RUN      ] Dense.ForwardCpp
[       OK ] Dense.ForwardCpp (0 ms)
[ RUN      ] Dense.BackwardCpp
[       OK ] Dense.BackwardCpp (0 ms)
[----------] 3 tests from Dense (0 ms total)

[----------] 3 tests from Dropout
[ RUN      ] Dropout.Setup
[       OK ] Dropout.Setup (0 ms)
[ RUN      ] Dropout.Forward
[       OK ] Dropout.Forward (0 ms)
[ RUN      ] Dropout.Backward
[       OK ] Dropout.Backward (0 ms)
[----------] 3 tests from Dropout (0 ms total)

[----------] 3 tests from Flatten
[ RUN      ] Flatten.Setup
[       OK ] Flatten.Setup (0 ms)
[ RUN      ] Flatten.ForwardCPU
[       OK ] Flatten.ForwardCPU (0 ms)
[ RUN      ] Flatten.BackwardCPU
[       OK ] Flatten.BackwardCPU (0 ms)
[----------] 3 tests from Flatten (0 ms total)

[----------] 5 tests from ImageTransformer
[ RUN      ] ImageTransformer.Setup
[       OK ] ImageTransformer.Setup (0 ms)
[ RUN      ] ImageTransformer.Apply3D
[       OK ] ImageTransformer.Apply3D (0 ms)
[ RUN      ] ImageTransformer.Apply2D
[       OK ] ImageTransformer.Apply2D (0 ms)
[ RUN      ] ImageTransformer.Crop
[       OK ] ImageTransformer.Crop (0 ms)
[ RUN      ] ImageTransformer.Mirror
[       OK ] ImageTransformer.Mirror (0 ms)
[----------] 5 tests from ImageTransformer (0 ms total)

[----------] 2 tests from Initializer
[ RUN      ] Initializer.Constant
[       OK ] Initializer.Constant (0 ms)
[ RUN      ] Initializer.Gaussian
[       OK ] Initializer.Gaussian (1 ms)
[----------] 2 tests from Initializer (1 ms total)

[----------] 1 test from Layer
[ RUN      ] Layer.CreateLayer
[       OK ] Layer.CreateLayer (0 ms)
[----------] 1 test from Layer (0 ms total)

[----------] 6 tests from Logging
[ RUN      ] Logging.InfoLogging
[I d0713 t11:31:57 p11482:344 /root/dcsysh/singa/test/singa/test_logging.cc:29] test info logging
[       OK ] Logging.InfoLogging (0 ms)
[ RUN      ] Logging.WarningLogging
[W d0713 t11:31:57 p11482:344 /root/dcsysh/singa/test/singa/test_logging.cc:35] test warning logging
[       OK ] Logging.WarningLogging (0 ms)
[ RUN      ] Logging.ErrorLogging
[E d0713 t11:31:57 p11482:344 /root/dcsysh/singa/test/singa/test_logging.cc:41] test error logging
[       OK ] Logging.ErrorLogging (0 ms)
[ RUN      ] Logging.FatalLogging
[       OK ] Logging.FatalLogging (0 ms)
[ RUN      ] Logging.SetLogDestination
[       OK ] Logging.SetLogDestination (0 ms)
[ RUN      ] Logging.StderrLoggingLevel
[W d0713 t11:31:57 p11482:344 /root/dcsysh/singa/test/singa/test_logging.cc:62] test warning logging to stderr and file
[E d0713 t11:31:57 p11482:344 /root/dcsysh/singa/test/singa/test_logging.cc:63] test error logging to stderr and file
[       OK ] Logging.StderrLoggingLevel (0 ms)
[----------] 6 tests from Logging (0 ms total)

[----------] 3 tests from LRN
[ RUN      ] LRN.Setup
[       OK ] LRN.Setup (0 ms)
[ RUN      ] LRN.Forward
[       OK ] LRN.Forward (0 ms)
[ RUN      ] LRN.Backward
[       OK ] LRN.Backward (1 ms)
[----------] 3 tests from LRN (1 ms total)

[----------] 2 tests from TestMSE
[ RUN      ] TestMSE.CppForward
[       OK ] TestMSE.CppForward (0 ms)
[ RUN      ] TestMSE.CppBackward
[       OK ] TestMSE.CppBackward (0 ms)
[----------] 2 tests from TestMSE (0 ms total)

[----------] 1 test from Nesterov
[ RUN      ] Nesterov.ApplyCPU
[       OK ] Nesterov.ApplyCPU (0 ms)
[----------] 1 test from Nesterov (0 ms total)

[----------] 3 tests from Pooling
[ RUN      ] Pooling.Setup
[       OK ] Pooling.Setup (0 ms)
[ RUN      ] Pooling.Forward
[       OK ] Pooling.Forward (0 ms)
[ RUN      ] Pooling.Backward
[       OK ] Pooling.Backward (0 ms)
[----------] 3 tests from Pooling (0 ms total)

[----------] 3 tests from PReLU
[ RUN      ] PReLU.Setup
[       OK ] PReLU.Setup (0 ms)
[ RUN      ] PReLU.ForwardCPU
[       OK ] PReLU.ForwardCPU (0 ms)
[ RUN      ] PReLU.BackwardCPU
[       OK ] PReLU.BackwardCPU (0 ms)
[----------] 3 tests from PReLU (0 ms total)

[----------] 1 test from RMSProp
[ RUN      ] RMSProp.ApplyCPU
[       OK ] RMSProp.ApplyCPU (0 ms)
[----------] 1 test from RMSProp (0 ms total)

[----------] 10 tests from TestGraph
[ RUN      ] TestGraph.AddOp
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.AddOp (0 ms)
[ RUN      ] TestGraph.AddSyncOp
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.AddSyncOp (0 ms)
[ RUN      ] TestGraph.AddInplaceOp
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.AddInplaceOp (1 ms)
[ RUN      ] TestGraph.BlockTypeInput
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.BlockTypeInput (0 ms)
[ RUN      ] TestGraph.BlockTypeParam
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.BlockTypeParam (0 ms)
[ RUN      ] TestGraph.BlockTypeInter
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.BlockTypeInter (0 ms)
[ RUN      ] TestGraph.BlockTypeEnd
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.BlockTypeEnd (0 ms)
[ RUN      ] TestGraph.RunGraph
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.RunGraph (0 ms)
[ RUN      ] TestGraph.RunInSerial
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.RunInSerial (0 ms)
[ RUN      ] TestGraph.AutoRecycle
[          ] Test graph on device [cpp_cpu]
[       OK ] TestGraph.AutoRecycle (0 ms)
[----------] 10 tests from TestGraph (1 ms total)

[----------] 2 tests from SGD
[ RUN      ] SGD.ApplyWithoutMomentum
[       OK ] SGD.ApplyWithoutMomentum (0 ms)
[ RUN      ] SGD.ApplyWithMomentum
[       OK ] SGD.ApplyWithMomentum (0 ms)
[----------] 2 tests from SGD (0 ms total)

[----------] 5 tests from Slice
[ RUN      ] Slice.Setup
[       OK ] Slice.Setup (0 ms)
[ RUN      ] Slice.ForwardSliceRowCpp
[       OK ] Slice.ForwardSliceRowCpp (0 ms)
[ RUN      ] Slice.ForwardSliceColumn
[       OK ] Slice.ForwardSliceColumn (0 ms)
[ RUN      ] Slice.BackwardSliceRowCpp
[       OK ] Slice.BackwardSliceRowCpp (1 ms)
[ RUN      ] Slice.BackwardSliceColumn
[       OK ] Slice.BackwardSliceColumn (0 ms)
[----------] 5 tests from Slice (1 ms total)

[----------] 3 tests from Snapshot
[ RUN      ] Snapshot.WriteTest
[       OK ] Snapshot.WriteTest (5 ms)
[ RUN      ] Snapshot.ReadTest
[       OK ] Snapshot.ReadTest (1 ms)
[ RUN      ] Snapshot.ReadIntTest
[       OK ] Snapshot.ReadIntTest (6 ms)
[----------] 3 tests from Snapshot (12 ms total)

[----------] 3 tests from Softmax
[ RUN      ] Softmax.Setup
[       OK ] Softmax.Setup (0 ms)
[ RUN      ] Softmax.Forward
[       OK ] Softmax.Forward (0 ms)
[ RUN      ] Softmax.Backward
[       OK ] Softmax.Backward (0 ms)
[----------] 3 tests from Softmax (0 ms total)

[----------] 13 tests from TensorClass
[ RUN      ] TensorClass.Constructor
[       OK ] TensorClass.Constructor (0 ms)
[ RUN      ] TensorClass.Reshape
[       OK ] TensorClass.Reshape (0 ms)
[ RUN      ] TensorClass.FloatAsTypeFloatCPU
[       OK ] TensorClass.FloatAsTypeFloatCPU (0 ms)
[ RUN      ] TensorClass.FloatAsTypeIntCPU
[       OK ] TensorClass.FloatAsTypeIntCPU (0 ms)
[ RUN      ] TensorClass.IntAsTypeFloatCPU
[       OK ] TensorClass.IntAsTypeFloatCPU (0 ms)
[ RUN      ] TensorClass.ToDevice
[       OK ] TensorClass.ToDevice (0 ms)
[ RUN      ] TensorClass.CopyDataFromHostPtr
[       OK ] TensorClass.CopyDataFromHostPtr (0 ms)
[ RUN      ] TensorClass.CopyData
[       OK ] TensorClass.CopyData (0 ms)
[ RUN      ] TensorClass.Clone
[       OK ] TensorClass.Clone (0 ms)
[ RUN      ] TensorClass.T
[       OK ] TensorClass.T (0 ms)
[ RUN      ] TensorClass.Repeat
[       OK ] TensorClass.Repeat (0 ms)
[ RUN      ] TensorClass.RepeatData
[       OK ] TensorClass.RepeatData (0 ms)
[ RUN      ] TensorClass.Broadcast
[       OK ] TensorClass.Broadcast (0 ms)
[----------] 13 tests from TensorClass (0 ms total)

[----------] 50 tests from TensorMath
[ RUN      ] TensorMath.AbsCpp
[       OK ] TensorMath.AbsCpp (1 ms)
[ RUN      ] TensorMath.ExpCpp
[       OK ] TensorMath.ExpCpp (0 ms)
[ RUN      ] TensorMath.ExpStrideCpp
[       OK ] TensorMath.ExpStrideCpp (0 ms)
[ RUN      ] TensorMath.LogCpp
[       OK ] TensorMath.LogCpp (0 ms)
[ RUN      ] TensorMath.ReLUCpp
[       OK ] TensorMath.ReLUCpp (0 ms)
[ RUN      ] TensorMath.SigmoidCpp
[       OK ] TensorMath.SigmoidCpp (0 ms)
[ RUN      ] TensorMath.SignCpp
[       OK ] TensorMath.SignCpp (0 ms)
[ RUN      ] TensorMath.SoftPlusCpp
[       OK ] TensorMath.SoftPlusCpp (0 ms)
[ RUN      ] TensorMath.SoftSignCpp
[       OK ] TensorMath.SoftSignCpp (0 ms)
[ RUN      ] TensorMath.SqrtCpp
[       OK ] TensorMath.SqrtCpp (0 ms)
[ RUN      ] TensorMath.SquareCpp
[       OK ] TensorMath.SquareCpp (0 ms)
[ RUN      ] TensorMath.TanhCpp
[       OK ] TensorMath.TanhCpp (0 ms)
[ RUN      ] TensorMath.SumCpp
[       OK ] TensorMath.SumCpp (0 ms)
[ RUN      ] TensorMath.SoftMaxCpp
[       OK ] TensorMath.SoftMaxCpp (0 ms)
[ RUN      ] TensorMath.LTCpp
[       OK ] TensorMath.LTCpp (0 ms)
[ RUN      ] TensorMath.LECpp
[       OK ] TensorMath.LECpp (0 ms)
[ RUN      ] TensorMath.GTCpp
[       OK ] TensorMath.GTCpp (0 ms)
[ RUN      ] TensorMath.GECpp
[       OK ] TensorMath.GECpp (0 ms)
[ RUN      ] TensorMath.EQCpp
[       OK ] TensorMath.EQCpp (0 ms)
[ RUN      ] TensorMath.PowCpp
[       OK ] TensorMath.PowCpp (0 ms)
[ RUN      ] TensorMath.SubCpp
[       OK ] TensorMath.SubCpp (0 ms)
[ RUN      ] TensorMath.EltwiseMultCpp
[       OK ] TensorMath.EltwiseMultCpp (0 ms)
[ RUN      ] TensorMath.DivCpp
[       OK ] TensorMath.DivCpp (0 ms)
[ RUN      ] TensorMath.BernoulliCpp
[       OK ] TensorMath.BernoulliCpp (1 ms)
[ RUN      ] TensorMath.UniformCpp
[       OK ] TensorMath.UniformCpp (1 ms)
[ RUN      ] TensorMath.GaussianCpp
[       OK ] TensorMath.GaussianCpp (5 ms)
[ RUN      ] TensorMath.AddTensorCpp
[       OK ] TensorMath.AddTensorCpp (0 ms)
[ RUN      ] TensorMath.AddTensorsCpp
[       OK ] TensorMath.AddTensorsCpp (0 ms)
[ RUN      ] TensorMath.SetValueCpp
[       OK ] TensorMath.SetValueCpp (0 ms)
[ RUN      ] TensorMath.ReshapeCpp
[       OK ] TensorMath.ReshapeCpp (0 ms)
[ RUN      ] TensorMath.TransposeReshapeCpp
[       OK ] TensorMath.TransposeReshapeCpp (0 ms)
[ RUN      ] TensorMath.TransposeFloatCpp
[       OK ] TensorMath.TransposeFloatCpp (0 ms)
[ RUN      ] TensorMath.TransposeIntCpp
[       OK ] TensorMath.TransposeIntCpp (0 ms)
[ RUN      ] TensorMath.BroadcastCpp
[       OK ] TensorMath.BroadcastCpp (0 ms)
[ RUN      ] TensorMath.L2Cpp
[       OK ] TensorMath.L2Cpp (0 ms)
[ RUN      ] TensorMath.MultCpp
[       OK ] TensorMath.MultCpp (0 ms)
[ RUN      ] TensorMath.AddColumnCpp
[       OK ] TensorMath.AddColumnCpp (0 ms)
[ RUN      ] TensorMath.SubColumnCpp
[       OK ] TensorMath.SubColumnCpp (0 ms)
[ RUN      ] TensorMath.DivColumnCpp
[       OK ] TensorMath.DivColumnCpp (0 ms)
[ RUN      ] TensorMath.AddRowCpp
[       OK ] TensorMath.AddRowCpp (0 ms)
[ RUN      ] TensorMath.SubRowCpp
[       OK ] TensorMath.SubRowCpp (0 ms)
[ RUN      ] TensorMath.MultRowCpp
[       OK ] TensorMath.MultRowCpp (0 ms)
[ RUN      ] TensorMath.MultColumnCpp
[       OK ] TensorMath.MultColumnCpp (0 ms)
[ RUN      ] TensorMath.DivRowCpp
[       OK ] TensorMath.DivRowCpp (0 ms)
[ RUN      ] TensorMath.SumRowsCpp
[       OK ] TensorMath.SumRowsCpp (0 ms)
[ RUN      ] TensorMath.SumColumnsCpp
[       OK ] TensorMath.SumColumnsCpp (1 ms)
[ RUN      ] TensorMath.ConcatenateRowsCpp
[       OK ] TensorMath.ConcatenateRowsCpp (0 ms)
[ RUN      ] TensorMath.ConcatenateColumnsCpp
[       OK ] TensorMath.ConcatenateColumnsCpp (0 ms)
[ RUN      ] TensorMath.CopyRowsCpp
[       OK ] TensorMath.CopyRowsCpp (0 ms)
[ RUN      ] TensorMath.CopyColumnsCpp
[       OK ] TensorMath.CopyColumnsCpp (0 ms)
[----------] 50 tests from TensorMath (9 ms total)

[----------] 2 tests from TextFileWriter
[ RUN      ] TextFileWriter.Create
[       OK ] TextFileWriter.Create (2 ms)
[ RUN      ] TextFileWriter.Append
[       OK ] TextFileWriter.Append (2 ms)
[----------] 2 tests from TextFileWriter (4 ms total)

[----------] 2 tests from TextFileReader
[ RUN      ] TextFileReader.Read
[       OK ] TextFileReader.Read (1 ms)
[ RUN      ] TextFileReader.SeekToFirst
[       OK ] TextFileReader.SeekToFirst (1 ms)
[----------] 2 tests from TextFileReader (2 ms total)

[----------] 1 test from TimerTest
[ RUN      ] TimerTest.TestTick
[       OK ] TimerTest.TestTick (10 ms)
[----------] 1 test from TimerTest (10 ms total)

[----------] Global test environment tear-down
[==========] 159 tests from 35 test cases ran. (284 ms total)
[  PASSED  ] 159 tests.

```

### CODE REVIEW

**Comment by moazreyad** [comment]
Great. Thanks.

Another little thing: the CheckLicence shows [errors](https://github.com/apache/singa/pull/765/checks?check_run_id=864966549#step:3:2871) files with missing Apache license header

```
[WARNING] Files with unapproved licenses:
  /home/runner/work/singa/singa/examples/rnn/imdb_model.py
  /home/runner/work/singa/singa/examples/rnn/imdb_train.py
  /home/runner/work/singa/singa/examples/rnn/imdb_data.py
  /home/runner/work/singa/singa/examples/onnx/training/model.json
```

**Comment by dcslin** [comment]
Hi @chrishkchris , after latest commit, testing softmax is ok. But a side note is that, some test are not correctly label when compiling with DNNL OFF, thus some test failed. is it the case?

**Comment by chrishkchris** [comment]
> Hi @chrishkchris , after latest commit, testing softmax is ok. But a side note is that, some test are not correctly label when compiling with DNNL OFF, thus some test failed. is it the case?

This PR fix two things:
1. c++ test: add back the kernal without DNNL: (i) if USE_DNNL=ON, use DNNL softmax kernal, if USE_DNNL=OFF, use the old kernal. Both can pass the test cases. The test was failed just because it did not have the kernal for the test

2. fix python test cases but those are not related to DNNL, for example, in opt_test.py:  
`sgd1.apply(w, w, g)` should be `sgd1.apply(w.name, w, g)` , the first argument is name

**Comment by dcslin** [comment]
> > Hi @chrishkchris , after latest commit, testing softmax is ok. But a side note is that, some test are not correctly label when compiling with DNNL OFF, thus some test failed. is it the case?
> 
> This PR fix two things:
> 
> 1. c++ test: add back the kernal without DNNL: (i) if USE_DNNL=ON, use DNNL softmax kernal, if USE_DNNL=OFF, use the old kernal. Both can pass the test cases. The test was failed just because it did not have the kernal for the test
> 2. fix python test cases but those are not related to DNNL, for example, in opt_test.py:
>    `sgd1.apply(w, w, g)` should be `sgd1.apply(w.name, w, g)` , the first argument is name

yes. I am ok with the change for the scope of this fix. I am ok to merge it if no more comment.

**Comment by chrishkchris** [comment]
thanks, I think this PR is ready for merge

**Pull request merged**
