### PR TITLE
added support for matmul 3d 4d

### PR DESCRIPTION
**Pull request by dcslin**

### CODE REVIEW

**Comment by dcslin** [comment]
fix issue: https://github.com/apache/singa/issues/634

**Comment by dcslin** [comment]
fix https://github.com/apache/singa/issues/634 follow up issue

**Comment by nudles** [comment]
is matmul different to tensordot?
why not call tensordot to implement it?

**Comment by nudles** [comment]
Is it called batched matmul or batched gemm?
Seems different to tensordot.
since the API for matmul remains the same, we may need to update the DocString.

**Comment by dcslin** [comment]
> is matmul different to tensordot?
> why not call tensordot to implement it?

Batch matmul could not be implemented by tensordot, as matmul is not really tensor dot.
Batch matmul could be illustrated by einsum:
``` python
>>> x1.shape
(2, 3, 4, 5)
>>> x2.shape
(2, 3, 5, 6)
>>> np.testing.assert_almost_equal(np.matmul(x1,x2), np.einsum('ijkl,ijlm->ijkm',x1,x2))
# output is (2,3,4,6)
```


Boardcasting matmul could be implemented by tensordot:
```
>>> x1.shape
(2, 3, 4, 5)
>>> x3.shape
(5, 6)
>>> np.testing.assert_almost_equal(np.matmul(x1,x3), np.tensordot(x1,x3,axes=([3],[0])))
# output is (2,3,4,6)
```

**Comment by dcslin** [comment]
> Is it called batched matmul or batched gemm?
> Seems different to tensordot.
> since the API for matmul remains the same, we may need to update the DocString.

In the high level API, `batch matmul` is ok, I see people calling it this way. In numpy, all `matmul` are call `matmul`.

In the low level API, cublas calls it `Batched GEMM`, cblas also does similarly.

I have update `singa/tensor.py` docstring to cover 3 cases:
1. 2d*1d matrix to vector
2. 2d*2d matrix to matrix
3. 3/4d*3/4d batched matrix to matrix

**Pull request merged**
