### PR TITLE
Update conda recipe to use conda dnnl

### PR DESCRIPTION
**Pull request by dcslin**

### CODE REVIEW

**Comment by chrishkchris** [comment]
seems great! only the macos version cannot find dnnl?

**Comment by chrishkchris** [comment]
the travis test results still cannot find "deprecated"
I think the "deprecated" should be put at "run" rather than "host" in conda_build_config.yaml, because it is used at runtime (while build process doesn't need).

**Comment by dcslin** [comment]
> the travis test results still cannot find "deprecated"
> I think the "deprecated" should be put at "run" rather than "host" in conda_build_config.yaml, because it is used at runtime (while build process doesn't need).

@chrishkchris thanks for the advice

**Comment by dcslin** [comment]
Should be ok now.

**Pull request merged**
