### PR TITLE
Improve graph compatibility

### PR DESCRIPTION
**Pull request by XJDKC**
Capture some tensors by value. These tensors will be recycled during the evaluation phase. But this PR may affect memory usage when enabling graph.

### CODE REVIEW

**Comment by XJDKC** [comment]
Many intermediate tensors are recorded which may affect the performance of automatic memory recycling. The scheduler won't recycle the tensor used on the Python side.
[example](https://github.com/apache/singa/blob/dev/python/singa/autograd.py#L2013)
x, mean and var are recorded on the Python side and they always exist after every iteration, so the scheduler won't recycle them, but they could have been recycled.

**Comment by nudles** [comment]
why do we need to capture some tensors by value and some by reference?

**Comment by XJDKC** [comment]
> why do we need to capture some tensors by value and some by reference?

This is exactly what I did before. But for the evaluation phase, tensors in the example will be recycled(It will create a new operation class by calling __call__ function, so the previous operations will be recycled and so do tensors they contain). If we access them in the next epoch, the program will crash.

**Comment by XJDKC** [comment]
I have fixed this issue, now the peak memory usage is even lower than the previous test. It probably saves another 0.5GB when training ResNet50.

**Pull request merged**
