### PR TITLE
add exp && round && rounde operators

### PR DESCRIPTION
**Pull request by joddiy**

### CODE REVIEW

**Comment by joddiy** [comment]
@dcslin Hi, shicong, can you help me implement the `round` and `rounde` operators in the c++, as you see, it's too complicated in python.

**Comment by dcslin** [comment]
Hi @joddiy , will this work for you? https://github.com/apache/singa/pull/749

**Comment by joddiy** [comment]
> Hi @joddiy , will this work for you? #749

seems not to work:

image

**Comment by joddiy** [comment]
> > Hi @joddiy , will this work for you? #749
> 
> seems not to work:
> 
> image

Hi, shicong, the `round` and `rounde` works now. However, the result of `rounde` is wrong now.

please use this test:
```
def rounde_helper(self, dev):
    X = np.array([0.1, 0.5, 0.9, 1.2, 1.5,
                1.8, 2.3, 2.5, 2.7, -1.1,
                -1.5, -1.9, -2.2, -2.5, -2.8]).astype(np.float32)
    x = tensor.from_numpy(X)
    x.to_device(dev)

    y_t = np.array([0., 0., 1., 1., 2.,
                2., 2., 2., 3., -1.,
                -2., -2., -2., -2., -3.]).astype(np.float32)
    dy = tensor.from_numpy(y_t)
    dy.to_device(dev)

    y = autograd.rounde(x)
    np.testing.assert_array_almost_equal(tensor.to_numpy(y), y_t)

def test_rounde_cpu(self):
    self.rounde_helper(cpu_dev)

@unittest.skipIf(not singa_wrap.USE_CUDA, 'CUDA is not enabled')
def test_rounde_gpu(self):
    self.rounde_helper(gpu_dev)
```

Specifically, Rounde(0.9) should be 1 instead of 0.

I guess the formula should be:
```
apply round(x / 2) * 2 if x == xxx.5 else round(x)
```

**Comment by chrishkchris** [comment]
I tested your code with your test case. 

```
root@71ac539cda77:~/dcsysh/singa/test/python# python3 test_operation.py TestPythonOperation.test_round_cpu
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
root@71ac539cda77:~/dcsysh/singa/test/python# python3 test_operation.py TestPythonOperation.test_round_gpu
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
root@71ac539cda77:~/dcsysh/singa/test/python# python3 test_operation.py TestPythonOperation.test_rounde_cpu
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
root@71ac539cda77:~/dcsysh/singa/test/python# python3 test_operation.py TestPythonOperation.test_rounde_gpu
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
```

The code looks good to me. So I merged the code.

**Pull request merged**
