### PR TITLE
fixed broadcast div pow

### PR DESCRIPTION
**Pull request by dcslin**
fixed div and pow operator when broadcasting
broadcast tests covered add, sub, mul, pow, div on transpose cases
ref. https://github.com/apache/singa/pull/545

### CODE REVIEW

**Comment by joddiy** [comment]
Hi, @dcslin it works fine, however, I saw a little difference between the results of numpy and singa(for pow based gpu and div based cpu).
```
Mismatch: 10%
Max absolute difference: 0.00073242
Max relative difference: 5.9753495e-07
 x: array([[-3.58730e+01, -9.22379e+03, -1.86656e+00,  1.22574e+03,
         1.13451e-01],
       [ 3.81203e+00, -1.25024e+01, -1.21589e+00,  1.68196e-01,...
 y: array([[-3.58730e+01, -9.22379e+03, -1.86656e+00,  1.22574e+03,
         1.13451e-01],
       [ 3.81203e+00, -1.25024e+01, -1.21589e+00,  1.68196e-01,...
```
Not too big, I guess the problem is caused by floating-point precision, is that ok? @nudles

**Comment by dcslin** [comment]
HI @joddiy ,thanks for the info, I added cpu tests, it works for me: https://github.com/apache/singa/pull/565/commits/14ab364c046411bc40de4ce823c00f069bef2150

maybe can share your test case?

**Comment by joddiy** [comment]
For div based cpu
```
        dev = cpu_dev
        cases = [
            ([3, 4, 5], [5]),  # 3d vs 1d
            ([3, 4, 5], [4, 5]),  # 3d vs 2d
            ([3, 4, 5, 6], [5, 6]),  # 4d vs 2d
            ([3, 4, 5, 6], [4, 5, 6]),  # 4d vs 3d
            ([1, 4, 1, 6], [3, 1, 5, 6])  # 4d vs 4d
        ]
        for in1, in2 in cases:
            x = np.random.randn(*in1).astype(np.float32)
            x1 = np.random.randn(*in2).astype(np.float32) + 1.0
            y = x / x1

            dy = np.random.randn(*y.shape).astype(np.float32)
            grad0 = np.sum(np.power(x1, -1) * dy, axis=axis_helper(y.shape, x.shape)).reshape(x.shape)
            grad1 = np.sum(x * - np.power(x1, -2) * dy, axis=axis_helper(y.shape, x1.shape)).reshape(x1.shape)
            
            x = tensor.from_numpy(x)
            x1 = tensor.from_numpy(x1)
            dy = tensor.from_numpy(dy)
            x.to_device(dev)
            x1.to_device(dev)
            dy.to_device(dev)

            result = autograd.div(x,x1)
            dx0,dx1 = result.creator.backward(dy.data)
            np.testing.assert_array_almost_equal(tensor.to_numpy(result), y, decimal=5)
            np.testing.assert_array_almost_equal(tensor.to_numpy(tensor.from_raw_tensor(dx0)), grad0, decimal=5)
            np.testing.assert_array_almost_equal(tensor.to_numpy(tensor.from_raw_tensor(dx1)), grad1, decimal=5)
```

For pow based gpu
```
        dev = gpu_dev
        cases = [
            ([3, 4, 5], [5]),  # 3d vs 1d
            ([3, 4, 5], [4, 5]),  # 3d vs 2d
            ([3, 4, 5, 6], [5, 6]),  # 4d vs 2d
            ([3, 4, 5, 6], [4, 5, 6]),  # 4d vs 3d
            ([1, 4, 1, 6], [3, 1, 5, 6])  # 4d vs 4d
        ]
        for in1, in2 in cases:
            x = np.random.randint(1, 10, size=in1).astype(np.float32)
            x1 = np.random.randint(1, 5, size=in2).astype(np.float32)
            y = np.power(x, x1).astype(np.float32)

            dy = np.random.randn(*y.shape).astype(np.float32)
            grad0 = np.sum(x1 * np.power(x, x1-1) * dy, axis=axis_helper(y.shape, x.shape)).reshape(x.shape)
            grad1 = np.sum(np.power(x, x1) * np.log(x) * dy, axis=axis_helper(y.shape, x1.shape)).reshape(x1.shape)
            
            x = tensor.from_numpy(x)
            x1 = tensor.from_numpy(x1)
            dy = tensor.from_numpy(dy)
            x.to_device(dev)
            x1.to_device(dev)
            dy.to_device(dev)

            result = autograd.pow(x,x1)
            dx0,dx1 = result.creator.backward(dy.data)
            np.testing.assert_array_almost_equal(tensor.to_numpy(result), y, decimal=5)
            np.testing.assert_array_almost_equal(tensor.to_numpy(tensor.from_raw_tensor(dx0)), grad0, decimal=5)
            np.testing.assert_array_almost_equal(tensor.to_numpy(tensor.from_raw_tensor(dx1)), grad1, decimal=5)
```

**Comment by dcslin** [comment]
refactored code to reuse similar structure. kudos to @chrishkchris .

**Comment by dcslin** [comment]
Hi @joddiy , I tried these cases, it looks fine at my end(forward pass)..

**Comment by joddiy** [comment]
Thanks, @dcslin, I think we can merge it firstly.

**Pull request merged**
