### PR TITLE
SINGA-333 Add ONNX backend test

### PR DESCRIPTION
**Pull request by moazreyad**

### CODE REVIEW

**Comment by nudles** [comment]
@joddiy  can we merge this one? or we need to wait until the operators are all implemented?

**Comment by joddiy** [comment]
I think we cannot directly use all the onnx test cases. Since, first, it's hard to integrate the sonnx into it. Second, there are lots of test cases we cannot use because we don't have some functionalities, such as dilation...
So far, I've written a new test file to adapt the test cases from onnx, so that we can discard some cases that we cannot implement.

**Comment by joddiy** [comment]
please refer to [here](https://github.com/apache/incubator-singa/pull/534)

**Comment by moazreyad** [comment]
But if we can't run onnx backend test cases, then we simply can't claim that we support onnx backend.

We don't have to pass all the test cases, but at least some of them should pass. Currently [all of the test cases fail](https://issues.apache.org/jira/projects/SINGA/issues/SINGA-458), which can be understood as if the current support of onnx backend is 0%.

**Comment by joddiy** [comment]
> But if we can't run onnx backend test cases, then we simply can't claim that we support onnx backend.
> 
> We don't have to pass all the test cases, but at least some of them should pass. Currently [all of the test cases fail](https://issues.apache.org/jira/projects/SINGA/issues/SINGA-458), which can be understood as if the current support of onnx backend is 0%.

Hi, moazreyad, I know what you mean. Please check the link [here](https://github.com/apache/incubator-singa/pull/534). I mean you cannot just easily call all the onnx test cases, it cannot run. I have adapted the onnx backend test cases from onnx there, and discard the cases that we cannot support.

**Pull request closed without merging**
