### PR TITLE
add Erf operator

### PR DESCRIPTION
**Pull request by dcslin**

### CODE REVIEW

**Comment by dcslin** [comment]
Hi @joddiy  https://github.com/apache/singa/issues/776 will this work for you?

**Comment by joddiy** [comment]
@dcslin  thanks, shicong, let me check.

**Comment by dcslin** [comment]
checking warnings

**Comment by dcslin** [comment]
it seems that LGTM warnings and CheckLicense errors are not introduced by this PR

**Comment by joddiy** [comment]
@dcslin Thanks shicong, it works fine.

**Pull request merged**
